spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ga9582619@gmail.com
spring.mail.password=rzjwijcvveroohce
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.protocol=smtp
# IMPORTANT: Use a Gmail App Password, not your regular password. Generate one at https://myaccount.google.com/apppasswords
